[package]
name = "malware_examples"
version = "0.1.0"
edition = "2021"
authors = ["Rayton Li <rayton.li@threatlocker.com>", "Nick Cottrell (J4bb3r) <nicholas.cottrell@threatlocker.com>"]
autobins = true

[dependencies]
base64 = "0.22.0"
rand = "0.9.0"
dns-lookup = "2.0.4"
reqwest = { version = "0.12.12", features = ["blocking"] }
diff = "0.1.13"
sysinfo = { version = "0.33.1", features = ["serde"] }
serde_json = "1.0.138"
regex = "1.11.1"
dirs = "6.0.0"
winreg = "0.55.0"
hex = "0.4.3"
clap = { version = "4.5.28", features = ["derive"] }


[profile.release]
strip = "symbols"
lto = "fat"
